# Generated by Django 2.2.5 on 2023-11-16 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.PositiveIntegerField()),
                ('comentario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Carona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_de_partida', models.CharField(max_length=100)),
                ('local_de_destino', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_de_partida', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('data_e_hora', models.DateTimeField()),
                ('assentos_disponiveis', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ride',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='passengers',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='driver',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='username',
            new_name='nome_de_usuario',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Usuario',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Ride',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.AddField(
            model_name='viagem',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usuario'),
        ),
        migrations.AddField(
            model_name='carona',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caronas_como_motorista', to='app.Usuario'),
        ),
        migrations.AddField(
            model_name='carona',
            name='passageiros',
            field=models.ManyToManyField(related_name='caronas_como_passageiro', to='app.Usuario'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='avaliador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usuario'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='usuario_avaliado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to='app.Usuario'),
        ),
    ]
