# Generated by Django 2.2.5 on 2023-12-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20231206_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='passengers',
            field=models.ManyToManyField(blank=True, related_name='trips_passenger', to='app.User'),
        ),
    ]
