# Generated by Django 2.2.5 on 2023-12-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_trip_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='passengers',
        ),
        migrations.AddField(
            model_name='trip',
            name='passengers',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
